%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright 2020 Xilinx
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
% http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



function polar_clip_config(this_block)

  % Revision History:
  %
  %   12-Jun-2020  (14:21 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /proj/xsjhdstaff4/abehbood/Model_Composer_Examples_3/lab8/polar_clip/solution1/impl/vhdl/polar_clip.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('polar_clip');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  % this_block.tagAsCombinational;

  this_block.addSimulinkInport('ap_rst_n');
  this_block.addSimulinkInport('in_sample_TDATA');
  this_block.addSimulinkInport('in_sample_TVALID');
  this_block.addSimulinkInport('in_sample_TKEEP');
  this_block.addSimulinkInport('in_sample_TSTRB');
  this_block.addSimulinkInport('in_sample_TLAST');
  this_block.addSimulinkInport('out_sample_TREADY');

  this_block.addSimulinkOutport('in_sample_TREADY');
  this_block.addSimulinkOutport('out_sample_TDATA');
  this_block.addSimulinkOutport('out_sample_TVALID');
  this_block.addSimulinkOutport('out_sample_TKEEP');
  this_block.addSimulinkOutport('out_sample_TSTRB');
  this_block.addSimulinkOutport('out_sample_TLAST');

  in_sample_TREADY_port = this_block.port('in_sample_TREADY');
  in_sample_TREADY_port.setType('UFix_1_0');
  in_sample_TREADY_port.useHDLVector(false);
  out_sample_TDATA_port = this_block.port('out_sample_TDATA');
  out_sample_TDATA_port.setType('UFix_32_0');
  out_sample_TVALID_port = this_block.port('out_sample_TVALID');
  out_sample_TVALID_port.setType('UFix_1_0');
  out_sample_TVALID_port.useHDLVector(false);
  out_sample_TKEEP_port = this_block.port('out_sample_TKEEP');
  out_sample_TKEEP_port.setType('UFix_4_0');
  out_sample_TSTRB_port = this_block.port('out_sample_TSTRB');
  out_sample_TSTRB_port.setType('UFix_4_0');
  out_sample_TLAST_port = this_block.port('out_sample_TLAST');
  out_sample_TLAST_port.setType('UFix_1_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('ap_rst_n').width ~= 1);
      this_block.setError('Input data type for port "ap_rst_n" must have width=1.');
    end

    this_block.port('ap_rst_n').useHDLVector(false);

    if (this_block.port('in_sample_TDATA').width ~= 32);
      this_block.setError('Input data type for port "in_sample_TDATA" must have width=32.');
    end

    if (this_block.port('in_sample_TVALID').width ~= 1);
      this_block.setError('Input data type for port "in_sample_TVALID" must have width=1.');
    end

    this_block.port('in_sample_TVALID').useHDLVector(false);

    if (this_block.port('in_sample_TKEEP').width ~= 4);
      this_block.setError('Input data type for port "in_sample_TKEEP" must have width=4.');
    end

    if (this_block.port('in_sample_TSTRB').width ~= 4);
      this_block.setError('Input data type for port "in_sample_TSTRB" must have width=4.');
    end

    if (this_block.port('in_sample_TLAST').width ~= 1);
      this_block.setError('Input data type for port "in_sample_TLAST" must have width=1.');
    end

    if (this_block.port('out_sample_TREADY').width ~= 1);
      this_block.setError('Input data type for port "out_sample_TREADY" must have width=1.');
    end

    this_block.port('out_sample_TREADY').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('polar_clip/solution1/impl/vhdl/polar_clip.vhd');
  this_block.addFile('polar_clip/solution1/impl/vhdl/polar_clip_mul_mul_16s_16s_32_4_1.vhd');
  this_block.addFile('polar_clip/solution1/impl/vhdl/polar_clip_mac_muladd_16s_16s_32s_32_4_1.vhd');
  this_block.addFile('polar_clip/solution1/impl/vhdl/polar_clip_mul_mul_10ns_25s_25_4_1.vhd');
  this_block.addFile('polar_clip/solution1/impl/vhdl/polar_clip_mul_mul_16s_16s_16_4_1.vhd');
  this_block.addFile('polar_clip/solution1/impl/vhdl/polar_clip_rotation_sin_lut.vhd');
  this_block.addFile('polar_clip/solution1/impl/vhdl/polar_clip_rotation_cos_lut.vhd');
  this_block.addFile('polar_clip/solution1/impl/vhdl/regslice_core.vhd');


return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------