#ifndef __INCLUDE_H__
#define __INCLUDE_H__

#define INTERPOLATOR27_INPUT_SAMPLES 128
#define INTERPOLATOR27_INPUT_MARGIN (16*4)
#define INTERPOLATOR27_COEFFICIENTS 16
#define INTERPOLATOR27_OUTPUT_SAMPLES (INTERPOLATOR27_INPUT_SAMPLES * 2)
#define INTERPOLATOR27_INPUT_BLOCK_SIZE (INTERPOLATOR27_INPUT_SAMPLES * 4)

#define POLAR_CLIP_INPUT_BLOCK_SIZE (INTERPOLATOR27_OUTPUT_SAMPLES * 4)
#define POLAR_CLIP_OUTPUT_SAMPLES (INTERPOLATOR27_OUTPUT_SAMPLES)

#define DECIMATOR27_INPUT_SAMPLES (POLAR_CLIP_OUTPUT_SAMPLES)
#define DECIMATOR27_INPUT_BLOCK_SIZE (DECIMATOR27_INPUT_SAMPLES*4)
#define DECIMATOR27_INPUT_MARGIN (32*4)
#define DECIMATOR27_COEFFICIENTS 16
#define DECIMATOR27_OUTPUT_SAMPLES (DECIMATOR27_INPUT_SAMPLES / 2)
#define DECIMATOR27_OUTPUT_BLOCK_SIZE (DECIMATOR27_OUTPUT_SAMPLES *4 )

#endif /* __INCLUDE_H__ */
