// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module GradientMag_XMC_120_160_1_s (
        ap_start,
        start_full_n,
        start_out,
        start_write,
        SobelFilter_XMC_out1_i_dout,
        SobelFilter_XMC_out1_i_empty_n,
        SobelFilter_XMC_out1_i_read,
        SobelFilter_XMC_out2_i_dout,
        SobelFilter_XMC_out2_i_empty_n,
        SobelFilter_XMC_out2_i_read,
        GradientMag_XMC_out1_i_din,
        GradientMag_XMC_out1_i_full_n,
        GradientMag_XMC_out1_i_write,
        ap_clk,
        ap_rst,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_start;
input   start_full_n;
output   start_out;
output   start_write;
input  [15:0] SobelFilter_XMC_out1_i_dout;
input   SobelFilter_XMC_out1_i_empty_n;
output   SobelFilter_XMC_out1_i_read;
input  [15:0] SobelFilter_XMC_out2_i_dout;
input   SobelFilter_XMC_out2_i_empty_n;
output   SobelFilter_XMC_out2_i_read;
output  [15:0] GradientMag_XMC_out1_i_din;
input   GradientMag_XMC_out1_i_full_n;
output   GradientMag_XMC_out1_i_write;
input   ap_clk;
input   ap_rst;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

reg start_write;

reg    real_start;
reg    start_once_reg;
wire    internal_ap_ready;
wire    GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_ap_start;
wire    GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_ap_done;
wire    GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_ap_continue;
wire    GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_ap_idle;
wire    GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_ap_ready;
wire    GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_SobelFilter_XMC_out1_i_read;
wire    GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_SobelFilter_XMC_out2_i_read;
wire   [15:0] GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_srcX_obj_data_din;
wire    GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_srcX_obj_data_write;
wire   [15:0] GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_srcY_obj_data_din;
wire    GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_srcY_obj_data_write;
wire    GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_start_out;
wire    GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_start_write;
wire    xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_ap_start;
wire    xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_ap_done;
wire    xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_ap_continue;
wire    xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_ap_idle;
wire    xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_ap_ready;
wire    xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_start_out;
wire    xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_start_write;
wire    xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_srcX_obj_449_read;
wire    xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_srcY_obj_450_read;
wire   [15:0] xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_dst_obj_451_din;
wire    xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_dst_obj_451_write;
wire    GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_ap_start;
wire    GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_ap_done;
wire    GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_ap_continue;
wire    GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_ap_idle;
wire    GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_ap_ready;
wire    GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_dst_obj_data_read;
wire   [15:0] GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_GradientMag_XMC_out1_i_din;
wire    GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_GradientMag_XMC_out1_i_write;
wire    srcX_obj_data_full_n;
wire   [15:0] srcX_obj_data_dout;
wire    srcX_obj_data_empty_n;
wire    srcY_obj_data_full_n;
wire   [15:0] srcY_obj_data_dout;
wire    srcY_obj_data_empty_n;
wire    dst_obj_data_full_n;
wire   [15:0] dst_obj_data_dout;
wire    dst_obj_data_empty_n;
wire    ap_sync_ready;
wire   [0:0] start_for_xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_din;
wire    start_for_xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_full_n;
wire   [0:0] start_for_xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_dout;
wire    start_for_xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_empty_n;
wire   [0:0] start_for_GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_din;
wire    start_for_GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_full_n;
wire   [0:0] start_for_GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_dout;
wire    start_for_GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
end

GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9 GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_ap_start),
    .start_full_n(start_for_xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_full_n),
    .ap_done(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_ap_done),
    .ap_continue(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_ap_continue),
    .ap_idle(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_ap_idle),
    .ap_ready(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_ap_ready),
    .SobelFilter_XMC_out1_i_dout(SobelFilter_XMC_out1_i_dout),
    .SobelFilter_XMC_out1_i_empty_n(SobelFilter_XMC_out1_i_empty_n),
    .SobelFilter_XMC_out1_i_read(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_SobelFilter_XMC_out1_i_read),
    .SobelFilter_XMC_out2_i_dout(SobelFilter_XMC_out2_i_dout),
    .SobelFilter_XMC_out2_i_empty_n(SobelFilter_XMC_out2_i_empty_n),
    .SobelFilter_XMC_out2_i_read(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_SobelFilter_XMC_out2_i_read),
    .srcX_obj_data_din(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_srcX_obj_data_din),
    .srcX_obj_data_full_n(srcX_obj_data_full_n),
    .srcX_obj_data_write(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_srcX_obj_data_write),
    .srcY_obj_data_din(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_srcY_obj_data_din),
    .srcY_obj_data_full_n(srcY_obj_data_full_n),
    .srcY_obj_data_write(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_srcY_obj_data_write),
    .start_out(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_start_out),
    .start_write(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_start_write)
);

xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_s xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_ap_start),
    .start_full_n(start_for_GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_full_n),
    .ap_done(xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_ap_done),
    .ap_continue(xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_ap_continue),
    .ap_idle(xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_ap_idle),
    .ap_ready(xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_ap_ready),
    .start_out(xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_start_out),
    .start_write(xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_start_write),
    .srcX_obj_449_dout(srcX_obj_data_dout),
    .srcX_obj_449_empty_n(srcX_obj_data_empty_n),
    .srcX_obj_449_read(xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_srcX_obj_449_read),
    .srcY_obj_450_dout(srcY_obj_data_dout),
    .srcY_obj_450_empty_n(srcY_obj_data_empty_n),
    .srcY_obj_450_read(xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_srcY_obj_450_read),
    .dst_obj_451_din(xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_dst_obj_451_din),
    .dst_obj_451_full_n(dst_obj_data_full_n),
    .dst_obj_451_write(xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_dst_obj_451_write)
);

GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10 GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_ap_start),
    .ap_done(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_ap_done),
    .ap_continue(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_ap_continue),
    .ap_idle(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_ap_idle),
    .ap_ready(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_ap_ready),
    .dst_obj_data_dout(dst_obj_data_dout),
    .dst_obj_data_empty_n(dst_obj_data_empty_n),
    .dst_obj_data_read(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_dst_obj_data_read),
    .GradientMag_XMC_out1_i_din(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_GradientMag_XMC_out1_i_din),
    .GradientMag_XMC_out1_i_full_n(GradientMag_XMC_out1_i_full_n),
    .GradientMag_XMC_out1_i_write(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_GradientMag_XMC_out1_i_write)
);

fifo_w16_d2_S_x srcX_obj_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_srcX_obj_data_din),
    .if_full_n(srcX_obj_data_full_n),
    .if_write(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_srcX_obj_data_write),
    .if_dout(srcX_obj_data_dout),
    .if_empty_n(srcX_obj_data_empty_n),
    .if_read(xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_srcX_obj_449_read)
);

fifo_w16_d2_S_x srcY_obj_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_srcY_obj_data_din),
    .if_full_n(srcY_obj_data_full_n),
    .if_write(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_srcY_obj_data_write),
    .if_dout(srcY_obj_data_dout),
    .if_empty_n(srcY_obj_data_empty_n),
    .if_read(xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_srcY_obj_450_read)
);

fifo_w16_d2_S_x dst_obj_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_dst_obj_451_din),
    .if_full_n(dst_obj_data_full_n),
    .if_write(xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_dst_obj_451_write),
    .if_dout(dst_obj_data_dout),
    .if_empty_n(dst_obj_data_empty_n),
    .if_read(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_dst_obj_data_read)
);

start_for_xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0 start_for_xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_din),
    .if_full_n(start_for_xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_full_n),
    .if_write(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_start_write),
    .if_dout(start_for_xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_dout),
    .if_empty_n(start_for_xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_empty_n),
    .if_read(xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_ap_ready)
);

start_for_GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0 start_for_GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_din),
    .if_full_n(start_for_GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_full_n),
    .if_write(xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_start_write),
    .if_dout(start_for_GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_dout),
    .if_empty_n(start_for_GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_empty_n),
    .if_read(GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

assign GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_ap_continue = ap_continue;

assign GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_ap_start = start_for_GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_empty_n;

assign GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_ap_continue = 1'b1;

assign GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_ap_start = real_start;

assign GradientMag_XMC_out1_i_din = GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_GradientMag_XMC_out1_i_din;

assign GradientMag_XMC_out1_i_write = GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_GradientMag_XMC_out1_i_write;

assign SobelFilter_XMC_out1_i_read = GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_SobelFilter_XMC_out1_i_read;

assign SobelFilter_XMC_out2_i_read = GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_SobelFilter_XMC_out2_i_read;

assign ap_done = GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_ap_done;

assign ap_idle = (xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_ap_idle & GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_ap_idle & GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_ap_idle);

assign ap_ready = GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_ap_ready;

assign ap_sync_ready = GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_93_1_proc9_U0_ap_ready;

assign internal_ap_ready = ap_sync_ready;

assign start_for_GradientMag_XMC_120_160_1_Loop_VITIS_LOOP_106_3_proc10_U0_din = 1'b1;

assign start_for_xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_din = 1'b1;

assign start_out = real_start;

assign xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_ap_continue = 1'b1;

assign xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_ap_start = start_for_xFMagnitudeKernel_2_2_120_160_3_3_1_5_5_160_2_U0_empty_n;

endmodule //GradientMag_XMC_120_160_1_s
