// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module SobelFilter_XMC_120_160_1_s (
        ap_start,
        start_full_n,
        start_out,
        start_write,
        Image_in_adapter_out1_dout,
        Image_in_adapter_out1_empty_n,
        Image_in_adapter_out1_read,
        SobelFilter_XMC_out1_i_din,
        SobelFilter_XMC_out1_i_full_n,
        SobelFilter_XMC_out1_i_write,
        SobelFilter_XMC_out2_i_din,
        SobelFilter_XMC_out2_i_full_n,
        SobelFilter_XMC_out2_i_write,
        ap_clk,
        ap_rst,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_start;
input   start_full_n;
output   start_out;
output   start_write;
input  [7:0] Image_in_adapter_out1_dout;
input   Image_in_adapter_out1_empty_n;
output   Image_in_adapter_out1_read;
output  [15:0] SobelFilter_XMC_out1_i_din;
input   SobelFilter_XMC_out1_i_full_n;
output   SobelFilter_XMC_out1_i_write;
output  [15:0] SobelFilter_XMC_out2_i_din;
input   SobelFilter_XMC_out2_i_full_n;
output   SobelFilter_XMC_out2_i_write;
input   ap_clk;
input   ap_rst;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

reg start_write;

reg    real_start;
reg    start_once_reg;
wire    internal_ap_ready;
wire    SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_ap_start;
wire    SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_ap_done;
wire    SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_ap_continue;
wire    SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_ap_idle;
wire    SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_ap_ready;
wire    SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_Image_in_adapter_out1_read;
wire   [7:0] SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_src_obj_data_din;
wire    SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_src_obj_data_write;
wire    SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_start_out;
wire    SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_start_write;
wire    Sobel_0_3_0_2_120_160_1_false_U0_ap_start;
wire    Sobel_0_3_0_2_120_160_1_false_U0_ap_done;
wire    Sobel_0_3_0_2_120_160_1_false_U0_ap_continue;
wire    Sobel_0_3_0_2_120_160_1_false_U0_ap_idle;
wire    Sobel_0_3_0_2_120_160_1_false_U0_ap_ready;
wire    Sobel_0_3_0_2_120_160_1_false_U0_start_out;
wire    Sobel_0_3_0_2_120_160_1_false_U0_start_write;
wire    Sobel_0_3_0_2_120_160_1_false_U0_src_obj_456_read;
wire   [15:0] Sobel_0_3_0_2_120_160_1_false_U0_dstx_obj_457_din;
wire    Sobel_0_3_0_2_120_160_1_false_U0_dstx_obj_457_write;
wire   [15:0] Sobel_0_3_0_2_120_160_1_false_U0_dsty_obj_458_din;
wire    Sobel_0_3_0_2_120_160_1_false_U0_dsty_obj_458_write;
wire    SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_ap_start;
wire    SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_ap_done;
wire    SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_ap_continue;
wire    SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_ap_idle;
wire    SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_ap_ready;
wire    SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_dstx_obj_data_read;
wire    SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_dsty_obj_data_read;
wire   [15:0] SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_SobelFilter_XMC_out1_i_din;
wire    SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_SobelFilter_XMC_out1_i_write;
wire   [15:0] SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_SobelFilter_XMC_out2_i_din;
wire    SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_SobelFilter_XMC_out2_i_write;
wire    src_obj_data_full_n;
wire   [7:0] src_obj_data_dout;
wire    src_obj_data_empty_n;
wire    dstx_obj_data_full_n;
wire   [15:0] dstx_obj_data_dout;
wire    dstx_obj_data_empty_n;
wire    dsty_obj_data_full_n;
wire   [15:0] dsty_obj_data_dout;
wire    dsty_obj_data_empty_n;
wire    ap_sync_ready;
wire   [0:0] start_for_Sobel_0_3_0_2_120_160_1_false_U0_din;
wire    start_for_Sobel_0_3_0_2_120_160_1_false_U0_full_n;
wire   [0:0] start_for_Sobel_0_3_0_2_120_160_1_false_U0_dout;
wire    start_for_Sobel_0_3_0_2_120_160_1_false_U0_empty_n;
wire   [0:0] start_for_SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_din;
wire    start_for_SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_full_n;
wire   [0:0] start_for_SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_dout;
wire    start_for_SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
end

SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7 SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_ap_start),
    .start_full_n(start_for_Sobel_0_3_0_2_120_160_1_false_U0_full_n),
    .ap_done(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_ap_done),
    .ap_continue(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_ap_continue),
    .ap_idle(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_ap_idle),
    .ap_ready(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_ap_ready),
    .Image_in_adapter_out1_dout(Image_in_adapter_out1_dout),
    .Image_in_adapter_out1_empty_n(Image_in_adapter_out1_empty_n),
    .Image_in_adapter_out1_read(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_Image_in_adapter_out1_read),
    .src_obj_data_din(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_src_obj_data_din),
    .src_obj_data_full_n(src_obj_data_full_n),
    .src_obj_data_write(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_src_obj_data_write),
    .start_out(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_start_out),
    .start_write(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_start_write)
);

Sobel_0_3_0_2_120_160_1_false_s Sobel_0_3_0_2_120_160_1_false_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Sobel_0_3_0_2_120_160_1_false_U0_ap_start),
    .start_full_n(start_for_SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_full_n),
    .ap_done(Sobel_0_3_0_2_120_160_1_false_U0_ap_done),
    .ap_continue(Sobel_0_3_0_2_120_160_1_false_U0_ap_continue),
    .ap_idle(Sobel_0_3_0_2_120_160_1_false_U0_ap_idle),
    .ap_ready(Sobel_0_3_0_2_120_160_1_false_U0_ap_ready),
    .start_out(Sobel_0_3_0_2_120_160_1_false_U0_start_out),
    .start_write(Sobel_0_3_0_2_120_160_1_false_U0_start_write),
    .src_obj_456_dout(src_obj_data_dout),
    .src_obj_456_empty_n(src_obj_data_empty_n),
    .src_obj_456_read(Sobel_0_3_0_2_120_160_1_false_U0_src_obj_456_read),
    .dstx_obj_457_din(Sobel_0_3_0_2_120_160_1_false_U0_dstx_obj_457_din),
    .dstx_obj_457_full_n(dstx_obj_data_full_n),
    .dstx_obj_457_write(Sobel_0_3_0_2_120_160_1_false_U0_dstx_obj_457_write),
    .dsty_obj_458_din(Sobel_0_3_0_2_120_160_1_false_U0_dsty_obj_458_din),
    .dsty_obj_458_full_n(dsty_obj_data_full_n),
    .dsty_obj_458_write(Sobel_0_3_0_2_120_160_1_false_U0_dsty_obj_458_write)
);

SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8 SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_ap_start),
    .ap_done(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_ap_done),
    .ap_continue(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_ap_continue),
    .ap_idle(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_ap_idle),
    .ap_ready(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_ap_ready),
    .dstx_obj_data_dout(dstx_obj_data_dout),
    .dstx_obj_data_empty_n(dstx_obj_data_empty_n),
    .dstx_obj_data_read(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_dstx_obj_data_read),
    .dsty_obj_data_dout(dsty_obj_data_dout),
    .dsty_obj_data_empty_n(dsty_obj_data_empty_n),
    .dsty_obj_data_read(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_dsty_obj_data_read),
    .SobelFilter_XMC_out1_i_din(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_SobelFilter_XMC_out1_i_din),
    .SobelFilter_XMC_out1_i_full_n(SobelFilter_XMC_out1_i_full_n),
    .SobelFilter_XMC_out1_i_write(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_SobelFilter_XMC_out1_i_write),
    .SobelFilter_XMC_out2_i_din(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_SobelFilter_XMC_out2_i_din),
    .SobelFilter_XMC_out2_i_full_n(SobelFilter_XMC_out2_i_full_n),
    .SobelFilter_XMC_out2_i_write(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_SobelFilter_XMC_out2_i_write)
);

fifo_w8_d2_S src_obj_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_src_obj_data_din),
    .if_full_n(src_obj_data_full_n),
    .if_write(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_src_obj_data_write),
    .if_dout(src_obj_data_dout),
    .if_empty_n(src_obj_data_empty_n),
    .if_read(Sobel_0_3_0_2_120_160_1_false_U0_src_obj_456_read)
);

fifo_w16_d2_S dstx_obj_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_0_3_0_2_120_160_1_false_U0_dstx_obj_457_din),
    .if_full_n(dstx_obj_data_full_n),
    .if_write(Sobel_0_3_0_2_120_160_1_false_U0_dstx_obj_457_write),
    .if_dout(dstx_obj_data_dout),
    .if_empty_n(dstx_obj_data_empty_n),
    .if_read(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_dstx_obj_data_read)
);

fifo_w16_d2_S dsty_obj_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_0_3_0_2_120_160_1_false_U0_dsty_obj_458_din),
    .if_full_n(dsty_obj_data_full_n),
    .if_write(Sobel_0_3_0_2_120_160_1_false_U0_dsty_obj_458_write),
    .if_dout(dsty_obj_data_dout),
    .if_empty_n(dsty_obj_data_empty_n),
    .if_read(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_dsty_obj_data_read)
);

start_for_Sobel_0_3_0_2_120_160_1_false_U0 start_for_Sobel_0_3_0_2_120_160_1_false_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Sobel_0_3_0_2_120_160_1_false_U0_din),
    .if_full_n(start_for_Sobel_0_3_0_2_120_160_1_false_U0_full_n),
    .if_write(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_start_write),
    .if_dout(start_for_Sobel_0_3_0_2_120_160_1_false_U0_dout),
    .if_empty_n(start_for_Sobel_0_3_0_2_120_160_1_false_U0_empty_n),
    .if_read(Sobel_0_3_0_2_120_160_1_false_U0_ap_ready)
);

start_for_SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0 start_for_SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_din),
    .if_full_n(start_for_SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_full_n),
    .if_write(Sobel_0_3_0_2_120_160_1_false_U0_start_write),
    .if_dout(start_for_SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_dout),
    .if_empty_n(start_for_SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_empty_n),
    .if_read(SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

assign Image_in_adapter_out1_read = SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_Image_in_adapter_out1_read;

assign SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_ap_continue = ap_continue;

assign SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_ap_start = start_for_SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_empty_n;

assign SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_ap_continue = 1'b1;

assign SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_ap_start = real_start;

assign SobelFilter_XMC_out1_i_din = SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_SobelFilter_XMC_out1_i_din;

assign SobelFilter_XMC_out1_i_write = SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_SobelFilter_XMC_out1_i_write;

assign SobelFilter_XMC_out2_i_din = SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_SobelFilter_XMC_out2_i_din;

assign SobelFilter_XMC_out2_i_write = SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_SobelFilter_XMC_out2_i_write;

assign Sobel_0_3_0_2_120_160_1_false_U0_ap_continue = 1'b1;

assign Sobel_0_3_0_2_120_160_1_false_U0_ap_start = start_for_Sobel_0_3_0_2_120_160_1_false_U0_empty_n;

assign ap_done = SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_ap_done;

assign ap_idle = (Sobel_0_3_0_2_120_160_1_false_U0_ap_idle & SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_ap_idle & SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_ap_idle);

assign ap_ready = SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_ap_ready;

assign ap_sync_ready = SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_94_1_proc7_U0_ap_ready;

assign internal_ap_ready = ap_sync_ready;

assign start_for_SobelFilter_XMC_120_160_1_Loop_VITIS_LOOP_104_3_proc8_U0_din = 1'b1;

assign start_for_Sobel_0_3_0_2_120_160_1_false_U0_din = 1'b1;

assign start_out = real_start;

endmodule //SobelFilter_XMC_120_160_1_s
