// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module xFGradientX3x3_0_3_s (
        ap_ready,
        t0,
        t2,
        m0,
        m2,
        b0,
        b2,
        ap_return
);


output   ap_ready;
input  [7:0] t0;
input  [7:0] t2;
input  [7:0] m0;
input  [7:0] m2;
input  [7:0] b0;
input  [7:0] b2;
output  [10:0] ap_return;

wire   [8:0] M00_fu_54_p3;
wire   [8:0] M01_fu_66_p3;
wire   [8:0] zext_ln232_4_fu_82_p1;
wire   [8:0] zext_ln232_fu_78_p1;
wire   [8:0] ret_fu_86_p2;
wire   [8:0] zext_ln232_6_fu_100_p1;
wire   [8:0] zext_ln232_5_fu_96_p1;
wire   [8:0] ret_2_fu_104_p2;
wire   [9:0] zext_ln60_fu_74_p1;
wire   [9:0] zext_ln59_fu_62_p1;
wire   [9:0] out_pix_7_fu_114_p2;
wire  signed [10:0] sext_ln66_fu_120_p1;
wire   [10:0] zext_ln61_fu_92_p1;
wire   [10:0] out_pix_8_fu_124_p2;
wire   [10:0] zext_ln62_fu_110_p1;

assign M00_fu_54_p3 = {{m0}, {1'd0}};

assign M01_fu_66_p3 = {{m2}, {1'd0}};

assign ap_ready = 1'b1;

assign ap_return = (out_pix_8_fu_124_p2 - zext_ln62_fu_110_p1);

assign out_pix_7_fu_114_p2 = (zext_ln60_fu_74_p1 - zext_ln59_fu_62_p1);

assign out_pix_8_fu_124_p2 = ($signed(sext_ln66_fu_120_p1) + $signed(zext_ln61_fu_92_p1));

assign ret_2_fu_104_p2 = (zext_ln232_6_fu_100_p1 + zext_ln232_5_fu_96_p1);

assign ret_fu_86_p2 = (zext_ln232_4_fu_82_p1 + zext_ln232_fu_78_p1);

assign sext_ln66_fu_120_p1 = $signed(out_pix_7_fu_114_p2);

assign zext_ln232_4_fu_82_p1 = b2;

assign zext_ln232_5_fu_96_p1 = t0;

assign zext_ln232_6_fu_100_p1 = b0;

assign zext_ln232_fu_78_p1 = t2;

assign zext_ln59_fu_62_p1 = M00_fu_54_p3;

assign zext_ln60_fu_74_p1 = M01_fu_66_p3;

assign zext_ln61_fu_92_p1 = ret_fu_86_p2;

assign zext_ln62_fu_110_p1 = ret_2_fu_104_p2;

endmodule //xFGradientX3x3_0_3_s
