-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity xFSobelFilter3x3_0_2_120_160_1_0_3_1_1_5_160_false_Pipeline_Col_Loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    src_obj_456_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    src_obj_456_empty_n : IN STD_LOGIC;
    src_obj_456_read : OUT STD_LOGIC;
    dstx_obj_457_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    dstx_obj_457_full_n : IN STD_LOGIC;
    dstx_obj_457_write : OUT STD_LOGIC;
    dsty_obj_458_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    dsty_obj_458_full_n : IN STD_LOGIC;
    dsty_obj_458_write : OUT STD_LOGIC;
    buf_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buf_V_ce0 : OUT STD_LOGIC;
    buf_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_V_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buf_V_ce1 : OUT STD_LOGIC;
    buf_V_we1 : OUT STD_LOGIC;
    buf_V_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buf_V_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buf_V_1_ce0 : OUT STD_LOGIC;
    buf_V_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_V_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buf_V_1_ce1 : OUT STD_LOGIC;
    buf_V_1_we1 : OUT STD_LOGIC;
    buf_V_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buf_V_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buf_V_2_ce0 : OUT STD_LOGIC;
    buf_V_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_V_2_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buf_V_2_ce1 : OUT STD_LOGIC;
    buf_V_2_we1 : OUT STD_LOGIC;
    buf_V_2_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    tp_V : IN STD_LOGIC_VECTOR (1 downto 0);
    mid_V : IN STD_LOGIC_VECTOR (1 downto 0);
    bottom_V : IN STD_LOGIC_VECTOR (1 downto 0);
    row_ind_V_cast : IN STD_LOGIC_VECTOR (1 downto 0);
    cmp_i_i517_i : IN STD_LOGIC_VECTOR (0 downto 0);
    src_buf3_V_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    src_buf3_V_1_out_ap_vld : OUT STD_LOGIC;
    p_Val2_2_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_Val2_2_out_ap_vld : OUT STD_LOGIC;
    p_Val2_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_Val2_1_out_ap_vld : OUT STD_LOGIC;
    src_buf1_V_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    src_buf1_V_1_out_ap_vld : OUT STD_LOGIC;
    p_Val2_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_Val2_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of xFSobelFilter3x3_0_2_120_160_1_0_3_1_1_5_160_false_Pipeline_Col_Loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv8_A0 : STD_LOGIC_VECTOR (7 downto 0) := "10100000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln216_reg_589 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i_i517_i_read_reg_558 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op48_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal icmp_ln1064_reg_615 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1064_reg_615_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln216_fu_355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal src_obj_456_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal dstx_obj_457_blk_n : STD_LOGIC;
    signal dsty_obj_458_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal row_ind_V_cast_read_reg_562 : STD_LOGIC_VECTOR (1 downto 0);
    signal bottom_V_read_reg_566 : STD_LOGIC_VECTOR (1 downto 0);
    signal col_V_1_reg_581 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_V_1_reg_581_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal col_V_1_reg_581_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln216_reg_589_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln216_reg_589_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln216_reg_589_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln216_reg_589_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_V_reg_593 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln1064_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1064_reg_615_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal src_buf1_V_fu_395_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf1_V_reg_619 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf2_V_fu_408_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf2_V_reg_625 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf3_V_fu_421_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf3_V_reg_631 : STD_LOGIC_VECTOR (7 downto 0);
    signal GradientValuesX_V_reg_637 : STD_LOGIC_VECTOR (15 downto 0);
    signal GradientValuesY_V_reg_642 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_condition_exit_pp0_iter5_stage0 : STD_LOGIC;
    signal call_ret_xFSobel3x3_1_1_0_3_s_fu_305_ap_ready : STD_LOGIC;
    signal call_ret_xFSobel3x3_1_1_0_3_s_fu_305_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_xFSobel3x3_1_1_0_3_s_fu_305_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln587_1_fu_372_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_fu_378_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln225_fu_384_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal col_V_fu_90 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_V_2_fu_361_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_col_V_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf1_V_2_fu_94 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf2_V_2_fu_98 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf3_V_2_fu_102 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf2_V_1_fu_106 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf1_V_1_fu_110 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf3_V_1_fu_114 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_481 : BOOLEAN;
    signal ap_condition_487 : BOOLEAN;
    signal ap_condition_491 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component xFSobel3x3_1_1_0_3_s IS
    port (
        ap_ready : OUT STD_LOGIC;
        p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read5 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read6 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read7 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read8 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read9 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read10 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read11 : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component mux_42_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    call_ret_xFSobel3x3_1_1_0_3_s_fu_305 : component xFSobel3x3_1_1_0_3_s
    port map (
        ap_ready => call_ret_xFSobel3x3_1_1_0_3_s_fu_305_ap_ready,
        p_read2 => src_buf1_V_2_fu_94,
        p_read5 => src_buf1_V_1_fu_110,
        p_read6 => src_buf1_V_reg_619,
        p_read7 => src_buf2_V_2_fu_98,
        p_read8 => src_buf2_V_reg_625,
        p_read9 => src_buf3_V_2_fu_102,
        p_read10 => src_buf3_V_1_fu_114,
        p_read11 => src_buf3_V_reg_631,
        ap_return_0 => call_ret_xFSobel3x3_1_1_0_3_s_fu_305_ap_return_0,
        ap_return_1 => call_ret_xFSobel3x3_1_1_0_3_s_fu_305_ap_return_1);

    mux_42_8_1_1_U29 : component mux_42_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buf_V_q0,
        din1 => buf_V_1_q0,
        din2 => buf_V_2_q0,
        din3 => ap_const_lv8_0,
        din4 => tp_V,
        dout => src_buf1_V_fu_395_p6);

    mux_42_8_1_1_U30 : component mux_42_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buf_V_q0,
        din1 => buf_V_1_q0,
        din2 => buf_V_2_q0,
        din3 => ap_const_lv8_0,
        din4 => mid_V,
        dout => src_buf2_V_fu_408_p6);

    mux_42_8_1_1_U31 : component mux_42_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buf_V_q0,
        din1 => buf_V_1_q0,
        din2 => buf_V_2_q0,
        din3 => ap_const_lv8_0,
        din4 => bottom_V,
        dout => src_buf3_V_fu_421_p6);

    flow_control_loop_pipe_sequential_init_U : component flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter5_stage0)) then 
                    ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    col_V_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln216_fu_355_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    col_V_fu_90 <= col_V_2_fu_361_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    col_V_fu_90 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    src_buf1_V_1_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    src_buf1_V_1_fu_110 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter4_reg = ap_const_lv1_0))) then 
                    src_buf1_V_1_fu_110 <= src_buf1_V_reg_619;
                end if;
            end if; 
        end if;
    end process;

    src_buf1_V_2_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    src_buf1_V_2_fu_94 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter4_reg = ap_const_lv1_0))) then 
                    src_buf1_V_2_fu_94 <= src_buf1_V_1_fu_110;
                end if;
            end if; 
        end if;
    end process;

    src_buf2_V_1_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    src_buf2_V_1_fu_106 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter4_reg = ap_const_lv1_0))) then 
                    src_buf2_V_1_fu_106 <= src_buf2_V_reg_625;
                end if;
            end if; 
        end if;
    end process;

    src_buf2_V_2_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    src_buf2_V_2_fu_98 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter4_reg = ap_const_lv1_0))) then 
                    src_buf2_V_2_fu_98 <= src_buf2_V_1_fu_106;
                end if;
            end if; 
        end if;
    end process;

    src_buf3_V_1_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    src_buf3_V_1_fu_114 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter4_reg = ap_const_lv1_0))) then 
                    src_buf3_V_1_fu_114 <= src_buf3_V_reg_631;
                end if;
            end if; 
        end if;
    end process;

    src_buf3_V_2_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    src_buf3_V_2_fu_102 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter4_reg = ap_const_lv1_0))) then 
                    src_buf3_V_2_fu_102 <= src_buf3_V_1_fu_114;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln216_reg_589_pp0_iter4_reg = ap_const_lv1_0))) then
                GradientValuesX_V_reg_637 <= call_ret_xFSobel3x3_1_1_0_3_s_fu_305_ap_return_0;
                GradientValuesY_V_reg_642 <= call_ret_xFSobel3x3_1_1_0_3_s_fu_305_ap_return_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                col_V_1_reg_581 <= ap_sig_allocacmp_col_V_1;
                col_V_1_reg_581_pp0_iter1_reg <= col_V_1_reg_581;
                icmp_ln216_reg_589 <= icmp_ln216_fu_355_p2;
                icmp_ln216_reg_589_pp0_iter1_reg <= icmp_ln216_reg_589;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                col_V_1_reg_581_pp0_iter2_reg <= col_V_1_reg_581_pp0_iter1_reg;
                icmp_ln1064_reg_615_pp0_iter4_reg <= icmp_ln1064_reg_615;
                icmp_ln1064_reg_615_pp0_iter5_reg <= icmp_ln1064_reg_615_pp0_iter4_reg;
                icmp_ln216_reg_589_pp0_iter2_reg <= icmp_ln216_reg_589_pp0_iter1_reg;
                icmp_ln216_reg_589_pp0_iter3_reg <= icmp_ln216_reg_589_pp0_iter2_reg;
                icmp_ln216_reg_589_pp0_iter4_reg <= icmp_ln216_reg_589_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln216_reg_589_pp0_iter2_reg = ap_const_lv1_0))) then
                icmp_ln1064_reg_615 <= icmp_ln1064_fu_390_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln216_reg_589_pp0_iter3_reg = ap_const_lv1_0))) then
                src_buf1_V_reg_619 <= src_buf1_V_fu_395_p6;
                src_buf2_V_reg_625 <= src_buf2_V_fu_408_p6;
                src_buf3_V_reg_631 <= src_buf3_V_fu_421_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op48_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_V_reg_593 <= src_obj_456_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter6, src_obj_456_empty_n, ap_predicate_op48_read_state2, dstx_obj_457_full_n, icmp_ln1064_reg_615_pp0_iter5_reg, dsty_obj_458_full_n)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (((dsty_obj_458_full_n = ap_const_logic_0) and (icmp_ln1064_reg_615_pp0_iter5_reg = ap_const_lv1_0)) or ((icmp_ln1064_reg_615_pp0_iter5_reg = ap_const_lv1_0) and (dstx_obj_457_full_n = ap_const_logic_0)))) or ((ap_predicate_op48_read_state2 = ap_const_boolean_1) and (src_obj_456_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter6, src_obj_456_empty_n, ap_predicate_op48_read_state2, dstx_obj_457_full_n, icmp_ln1064_reg_615_pp0_iter5_reg, dsty_obj_458_full_n)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (((dsty_obj_458_full_n = ap_const_logic_0) and (icmp_ln1064_reg_615_pp0_iter5_reg = ap_const_lv1_0)) or ((icmp_ln1064_reg_615_pp0_iter5_reg = ap_const_lv1_0) and (dstx_obj_457_full_n = ap_const_logic_0)))) or ((ap_predicate_op48_read_state2 = ap_const_boolean_1) and (src_obj_456_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter6, src_obj_456_empty_n, ap_predicate_op48_read_state2, dstx_obj_457_full_n, icmp_ln1064_reg_615_pp0_iter5_reg, dsty_obj_458_full_n)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (((dsty_obj_458_full_n = ap_const_logic_0) and (icmp_ln1064_reg_615_pp0_iter5_reg = ap_const_lv1_0)) or ((icmp_ln1064_reg_615_pp0_iter5_reg = ap_const_lv1_0) and (dstx_obj_457_full_n = ap_const_logic_0)))) or ((ap_predicate_op48_read_state2 = ap_const_boolean_1) and (src_obj_456_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(src_obj_456_empty_n, ap_predicate_op48_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((ap_predicate_op48_read_state2 = ap_const_boolean_1) and (src_obj_456_empty_n = ap_const_logic_0));
    end process;

        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state7_pp0_stage0_iter6_assign_proc : process(dstx_obj_457_full_n, icmp_ln1064_reg_615_pp0_iter5_reg, dsty_obj_458_full_n)
    begin
                ap_block_state7_pp0_stage0_iter6 <= (((dsty_obj_458_full_n = ap_const_logic_0) and (icmp_ln1064_reg_615_pp0_iter5_reg = ap_const_lv1_0)) or ((icmp_ln1064_reg_615_pp0_iter5_reg = ap_const_lv1_0) and (dstx_obj_457_full_n = ap_const_logic_0)));
    end process;


    ap_condition_481_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, icmp_ln216_reg_589_pp0_iter1_reg)
    begin
                ap_condition_481 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_condition_487_assign_proc : process(cmp_i_i517_i_read_reg_558, bottom_V_read_reg_566)
    begin
                ap_condition_487 <= (not((bottom_V_read_reg_566 = ap_const_lv2_0)) and not((bottom_V_read_reg_566 = ap_const_lv2_1)) and (cmp_i_i517_i_read_reg_558 = ap_const_lv1_0));
    end process;


    ap_condition_491_assign_proc : process(cmp_i_i517_i, row_ind_V_cast_read_reg_562)
    begin
                ap_condition_491 <= (not((row_ind_V_cast_read_reg_562 = ap_const_lv2_0)) and not((row_ind_V_cast_read_reg_562 = ap_const_lv2_1)) and (cmp_i_i517_i = ap_const_lv1_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln216_fu_355_p2)
    begin
        if (((icmp_ln216_fu_355_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter5_stage0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_subdone, icmp_ln216_reg_589_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter4_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter5_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter5_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_predicate_op48_read_state2_assign_proc : process(icmp_ln216_reg_589, cmp_i_i517_i)
    begin
                ap_predicate_op48_read_state2 <= ((cmp_i_i517_i = ap_const_lv1_1) and (icmp_ln216_reg_589 = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_col_V_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, col_V_fu_90, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_col_V_1 <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_col_V_1 <= col_V_fu_90;
        end if; 
    end process;

    bottom_V_read_reg_566 <= bottom_V;
    buf_V_1_address0 <= zext_ln225_fu_384_p1(8 - 1 downto 0);

    buf_V_1_address1_assign_proc : process(cmp_i_i517_i_read_reg_558, cmp_i_i517_i, row_ind_V_cast_read_reg_562, bottom_V_read_reg_566, zext_ln587_1_fu_372_p1, zext_ln587_fu_378_p1, ap_condition_481)
    begin
        if ((ap_const_boolean_1 = ap_condition_481)) then
            if (((cmp_i_i517_i = ap_const_lv1_1) and (row_ind_V_cast_read_reg_562 = ap_const_lv2_1))) then 
                buf_V_1_address1 <= zext_ln587_fu_378_p1(8 - 1 downto 0);
            elsif (((cmp_i_i517_i_read_reg_558 = ap_const_lv1_0) and (bottom_V_read_reg_566 = ap_const_lv2_1))) then 
                buf_V_1_address1 <= zext_ln587_1_fu_372_p1(8 - 1 downto 0);
            else 
                buf_V_1_address1 <= "XXXXXXXX";
            end if;
        else 
            buf_V_1_address1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_V_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            buf_V_1_ce0 <= ap_const_logic_1;
        else 
            buf_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_1_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, cmp_i_i517_i_read_reg_558, cmp_i_i517_i, ap_block_pp0_stage0_11001, row_ind_V_cast_read_reg_562, bottom_V_read_reg_566, icmp_ln216_reg_589_pp0_iter1_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i517_i = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter1_reg = ap_const_lv1_0) and (row_ind_V_cast_read_reg_562 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i517_i_read_reg_558 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter1_reg = ap_const_lv1_0) and (bottom_V_read_reg_566 = ap_const_lv2_1)))) then 
            buf_V_1_ce1 <= ap_const_logic_1;
        else 
            buf_V_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_1_d1_assign_proc : process(cmp_i_i517_i_read_reg_558, cmp_i_i517_i, row_ind_V_cast_read_reg_562, bottom_V_read_reg_566, tmp_V_reg_593, ap_condition_481)
    begin
        if ((ap_const_boolean_1 = ap_condition_481)) then
            if (((cmp_i_i517_i = ap_const_lv1_1) and (row_ind_V_cast_read_reg_562 = ap_const_lv2_1))) then 
                buf_V_1_d1 <= tmp_V_reg_593;
            elsif (((cmp_i_i517_i_read_reg_558 = ap_const_lv1_0) and (bottom_V_read_reg_566 = ap_const_lv2_1))) then 
                buf_V_1_d1 <= ap_const_lv8_0;
            else 
                buf_V_1_d1 <= "XXXXXXXX";
            end if;
        else 
            buf_V_1_d1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_V_1_we1_assign_proc : process(ap_enable_reg_pp0_iter2, cmp_i_i517_i_read_reg_558, cmp_i_i517_i, ap_block_pp0_stage0_11001, row_ind_V_cast_read_reg_562, bottom_V_read_reg_566, icmp_ln216_reg_589_pp0_iter1_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i517_i = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter1_reg = ap_const_lv1_0) and (row_ind_V_cast_read_reg_562 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i517_i_read_reg_558 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter1_reg = ap_const_lv1_0) and (bottom_V_read_reg_566 = ap_const_lv2_1)))) then 
            buf_V_1_we1 <= ap_const_logic_1;
        else 
            buf_V_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_2_address0 <= zext_ln225_fu_384_p1(8 - 1 downto 0);

    buf_V_2_address1_assign_proc : process(zext_ln587_1_fu_372_p1, zext_ln587_fu_378_p1, ap_condition_481, ap_condition_487, ap_condition_491)
    begin
        if ((ap_const_boolean_1 = ap_condition_481)) then
            if ((ap_const_boolean_1 = ap_condition_491)) then 
                buf_V_2_address1 <= zext_ln587_fu_378_p1(8 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_487)) then 
                buf_V_2_address1 <= zext_ln587_1_fu_372_p1(8 - 1 downto 0);
            else 
                buf_V_2_address1 <= "XXXXXXXX";
            end if;
        else 
            buf_V_2_address1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_V_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            buf_V_2_ce0 <= ap_const_logic_1;
        else 
            buf_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_2_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, cmp_i_i517_i_read_reg_558, cmp_i_i517_i, ap_block_pp0_stage0_11001, row_ind_V_cast_read_reg_562, bottom_V_read_reg_566, icmp_ln216_reg_589_pp0_iter1_reg)
    begin
        if (((not((row_ind_V_cast_read_reg_562 = ap_const_lv2_0)) and not((row_ind_V_cast_read_reg_562 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i517_i = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter1_reg = ap_const_lv1_0)) or (not((bottom_V_read_reg_566 = ap_const_lv2_0)) and not((bottom_V_read_reg_566 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i517_i_read_reg_558 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter1_reg = ap_const_lv1_0)))) then 
            buf_V_2_ce1 <= ap_const_logic_1;
        else 
            buf_V_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_2_d1_assign_proc : process(tmp_V_reg_593, ap_condition_481, ap_condition_487, ap_condition_491)
    begin
        if ((ap_const_boolean_1 = ap_condition_481)) then
            if ((ap_const_boolean_1 = ap_condition_491)) then 
                buf_V_2_d1 <= tmp_V_reg_593;
            elsif ((ap_const_boolean_1 = ap_condition_487)) then 
                buf_V_2_d1 <= ap_const_lv8_0;
            else 
                buf_V_2_d1 <= "XXXXXXXX";
            end if;
        else 
            buf_V_2_d1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_V_2_we1_assign_proc : process(ap_enable_reg_pp0_iter2, cmp_i_i517_i_read_reg_558, cmp_i_i517_i, ap_block_pp0_stage0_11001, row_ind_V_cast_read_reg_562, bottom_V_read_reg_566, icmp_ln216_reg_589_pp0_iter1_reg)
    begin
        if (((not((row_ind_V_cast_read_reg_562 = ap_const_lv2_0)) and not((row_ind_V_cast_read_reg_562 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i517_i = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter1_reg = ap_const_lv1_0)) or (not((bottom_V_read_reg_566 = ap_const_lv2_0)) and not((bottom_V_read_reg_566 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i517_i_read_reg_558 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter1_reg = ap_const_lv1_0)))) then 
            buf_V_2_we1 <= ap_const_logic_1;
        else 
            buf_V_2_we1 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_address0 <= zext_ln225_fu_384_p1(8 - 1 downto 0);

    buf_V_address1_assign_proc : process(cmp_i_i517_i_read_reg_558, cmp_i_i517_i, row_ind_V_cast_read_reg_562, bottom_V_read_reg_566, zext_ln587_1_fu_372_p1, zext_ln587_fu_378_p1, ap_condition_481)
    begin
        if ((ap_const_boolean_1 = ap_condition_481)) then
            if (((cmp_i_i517_i = ap_const_lv1_1) and (row_ind_V_cast_read_reg_562 = ap_const_lv2_0))) then 
                buf_V_address1 <= zext_ln587_fu_378_p1(8 - 1 downto 0);
            elsif (((cmp_i_i517_i_read_reg_558 = ap_const_lv1_0) and (bottom_V_read_reg_566 = ap_const_lv2_0))) then 
                buf_V_address1 <= zext_ln587_1_fu_372_p1(8 - 1 downto 0);
            else 
                buf_V_address1 <= "XXXXXXXX";
            end if;
        else 
            buf_V_address1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            buf_V_ce0 <= ap_const_logic_1;
        else 
            buf_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, cmp_i_i517_i_read_reg_558, cmp_i_i517_i, ap_block_pp0_stage0_11001, row_ind_V_cast_read_reg_562, bottom_V_read_reg_566, icmp_ln216_reg_589_pp0_iter1_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i517_i = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter1_reg = ap_const_lv1_0) and (row_ind_V_cast_read_reg_562 = ap_const_lv2_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i517_i_read_reg_558 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter1_reg = ap_const_lv1_0) and (bottom_V_read_reg_566 = ap_const_lv2_0)))) then 
            buf_V_ce1 <= ap_const_logic_1;
        else 
            buf_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_d1_assign_proc : process(cmp_i_i517_i_read_reg_558, cmp_i_i517_i, row_ind_V_cast_read_reg_562, bottom_V_read_reg_566, tmp_V_reg_593, ap_condition_481)
    begin
        if ((ap_const_boolean_1 = ap_condition_481)) then
            if (((cmp_i_i517_i = ap_const_lv1_1) and (row_ind_V_cast_read_reg_562 = ap_const_lv2_0))) then 
                buf_V_d1 <= tmp_V_reg_593;
            elsif (((cmp_i_i517_i_read_reg_558 = ap_const_lv1_0) and (bottom_V_read_reg_566 = ap_const_lv2_0))) then 
                buf_V_d1 <= ap_const_lv8_0;
            else 
                buf_V_d1 <= "XXXXXXXX";
            end if;
        else 
            buf_V_d1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_V_we1_assign_proc : process(ap_enable_reg_pp0_iter2, cmp_i_i517_i_read_reg_558, cmp_i_i517_i, ap_block_pp0_stage0_11001, row_ind_V_cast_read_reg_562, bottom_V_read_reg_566, icmp_ln216_reg_589_pp0_iter1_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i517_i = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter1_reg = ap_const_lv1_0) and (row_ind_V_cast_read_reg_562 = ap_const_lv2_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp_i_i517_i_read_reg_558 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln216_reg_589_pp0_iter1_reg = ap_const_lv1_0) and (bottom_V_read_reg_566 = ap_const_lv2_0)))) then 
            buf_V_we1 <= ap_const_logic_1;
        else 
            buf_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    cmp_i_i517_i_read_reg_558 <= cmp_i_i517_i;
    col_V_2_fu_361_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_col_V_1) + unsigned(ap_const_lv8_1));

    dstx_obj_457_blk_n_assign_proc : process(ap_enable_reg_pp0_iter6, dstx_obj_457_full_n, icmp_ln1064_reg_615_pp0_iter5_reg, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln1064_reg_615_pp0_iter5_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            dstx_obj_457_blk_n <= dstx_obj_457_full_n;
        else 
            dstx_obj_457_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dstx_obj_457_din <= GradientValuesX_V_reg_637;

    dstx_obj_457_write_assign_proc : process(ap_enable_reg_pp0_iter6, icmp_ln1064_reg_615_pp0_iter5_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1064_reg_615_pp0_iter5_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            dstx_obj_457_write <= ap_const_logic_1;
        else 
            dstx_obj_457_write <= ap_const_logic_0;
        end if; 
    end process;


    dsty_obj_458_blk_n_assign_proc : process(ap_enable_reg_pp0_iter6, icmp_ln1064_reg_615_pp0_iter5_reg, dsty_obj_458_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln1064_reg_615_pp0_iter5_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            dsty_obj_458_blk_n <= dsty_obj_458_full_n;
        else 
            dsty_obj_458_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dsty_obj_458_din <= GradientValuesY_V_reg_642;

    dsty_obj_458_write_assign_proc : process(ap_enable_reg_pp0_iter6, icmp_ln1064_reg_615_pp0_iter5_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1064_reg_615_pp0_iter5_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            dsty_obj_458_write <= ap_const_logic_1;
        else 
            dsty_obj_458_write <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1064_fu_390_p2 <= "1" when (col_V_1_reg_581_pp0_iter2_reg = ap_const_lv8_0) else "0";
    icmp_ln216_fu_355_p2 <= "1" when (ap_sig_allocacmp_col_V_1 = ap_const_lv8_A0) else "0";
    p_Val2_1_out <= src_buf2_V_2_fu_98;

    p_Val2_1_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln216_reg_589_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln216_reg_589_pp0_iter4_reg = ap_const_lv1_1))) then 
            p_Val2_1_out_ap_vld <= ap_const_logic_1;
        else 
            p_Val2_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_Val2_2_out <= src_buf3_V_2_fu_102;

    p_Val2_2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln216_reg_589_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln216_reg_589_pp0_iter4_reg = ap_const_lv1_1))) then 
            p_Val2_2_out_ap_vld <= ap_const_logic_1;
        else 
            p_Val2_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_Val2_out <= src_buf1_V_2_fu_94;

    p_Val2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln216_reg_589_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln216_reg_589_pp0_iter4_reg = ap_const_lv1_1))) then 
            p_Val2_out_ap_vld <= ap_const_logic_1;
        else 
            p_Val2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    row_ind_V_cast_read_reg_562 <= row_ind_V_cast;
    src_buf1_V_1_out <= src_buf1_V_1_fu_110;

    src_buf1_V_1_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln216_reg_589_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln216_reg_589_pp0_iter4_reg = ap_const_lv1_1))) then 
            src_buf1_V_1_out_ap_vld <= ap_const_logic_1;
        else 
            src_buf1_V_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    src_buf3_V_1_out <= src_buf3_V_1_fu_114;

    src_buf3_V_1_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln216_reg_589_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln216_reg_589_pp0_iter4_reg = ap_const_lv1_1))) then 
            src_buf3_V_1_out_ap_vld <= ap_const_logic_1;
        else 
            src_buf3_V_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    src_obj_456_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, src_obj_456_empty_n, ap_predicate_op48_read_state2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op48_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            src_obj_456_blk_n <= src_obj_456_empty_n;
        else 
            src_obj_456_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    src_obj_456_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op48_read_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op48_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            src_obj_456_read <= ap_const_logic_1;
        else 
            src_obj_456_read <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln225_fu_384_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_V_1_reg_581_pp0_iter2_reg),64));
    zext_ln587_1_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_V_1_reg_581_pp0_iter1_reg),64));
    zext_ln587_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_V_1_reg_581_pp0_iter1_reg),64));
end behav;
